apiVersion: v1
kind: Secret
metadata:
  name: stratroom-secrets
  namespace: stratroom-prod
type: Opaque
stringData:
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  JWT_SECRET: ${JWT_SECRET}
  JASYPT_PASSWORD: ${JASYPT_PASSWORD}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  # Add MAIL_SMTP_PASSWORD and LDAP_BIND_PASSWORD here if needed
